<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\dotnet.core.utils\dotnet.core.utils.csproj" />
    <ProjectReference Include="..\dotnet.core.thegoldenfan\dotnet.core.thegoldenfan.csproj" />
  </ItemGroup>

</Project>
